export const data = [
  {
    postId: "2",
    Title: "MODERN APPARTEMENT",
    description: "very nice appartement",
    prix: "350",
    ville: "Tetouan",
    gender: "homme",
    dateDePublication: "2012-04-23",
    dureeDeDisponibilite: "10days",
    nombreDeCollegues: "2",
    student: {
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      firstName: "Amine",
      lastName: "BIADA",
      email: "aminebiada98@gmail.com",
      image: "im an image",
      password: "123456",
      gender: "homme",
    },
    images: [
      {
        imageId: "U8ttwpfhM4exDxoqxWlQhBWir6aPb1",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
      {
        imageId: "ShFft66r3XaeqpTVBcADkrrpqMPChd",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
      {
        imageId: "DitmeOMzktWiokC4zHKikXnuaYbLvH",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
    ],
    details: {
      postDetailsId: "w5o9IQlXvvm3iq5d3st78I1gL2N5Pd",
      machineLaver: "Disponnible",
      refrigerateur: "Disponnible",
      television: "Pas Disponnible",
      chauffeEau: "disponible",
      internetAccess: "Disponnible",
      fibreOptique: "Pas Disponnible",
      autorisationFumer: null,
      etage: "3eme",
      ascenseur: "Disponnible",
      conditions: ["non smoker", "clean", "ensa student", "organized"],
    },
    location: {
      locationId: "sAMbvwAPhNab7ufNz2MqBlcvFHgz1X",
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      coordinates: [-5.36, 35.56],
    },
  },
  {
    postId: "3",
    description: "very nice appartement come check",
    prix: "4500",
    Title: "MODERN APPARTEMENT",
    ville: "Martil",
    gender: "homme",
    dateDePublication: "2012-04-23",
    dureeDeDisponibilite: "10days",
    nombreDeCollegues: "2",
    student: {
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      firstName: "Said",
      lastName: "JERADA",
      email: "aminebiada98@gmail.com",
      image: "im an image",
      password: "123456",
      gender: "homme",
    },
    images: [
      {
        imageId: "U8ttwpfhM4exDxoqxWlQhBWir6aPb1",
        url: "https://delormdesign.com/blog/wp-content/uploads/2018/07/canape-design-italien-tissu-pratique.jpg",
      },
      {
        imageId: "ShFft66r3XaeqpTVBcADkrrpqMPChd",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
      {
        imageId: "DitmeOMzktWiokC4zHKikXnuaYbLvH",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
    ],
    details: {
      postDetailsId: "w5o9IQlXvvm3iq5d3st78I1gL2N5Pd",
      machineLaver: "Disponnible",
      refrigerateur: "Disponnible",
      television: "Pas Disponnible",
      chauffeEau: "disponible",
      internetAccess: "Disponnible",
      fibreOptique: "Pas Disponnible",
      autorisationFumer: null,
      etage: "3eme",
      ascenseur: "Disponnible",
      conditions: ["non smoker", "clean", "ensa student", "organized"],
    },
    location: {
      locationId: "sAMbvwAPhNab7ufNz2MqBlcvFHgz1X",
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      coordinates: [-5, 35],
    },
  },
  {
    postId: "4",
    description: "very nice appartement",
    prix: "6000",
    Title: "MODERN APPARTEMENT",
    ville: "Fnideq",
    gender: "homme",
    dateDePublication: "2012-04-23",
    dureeDeDisponibilite: "10days",
    nombreDeCollegues: "2",
    student: {
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      firstName: "Othman",
      lastName: "BSSEL",
      email: "aminebiada98@gmail.com",
      image: "im an image",
      password: "123456",
      gender: "homme",
    },
    images: [
      {
        imageId: "U8ttwpfhM4exDxoqxWlQhBWir6aPb1",
        url: "https://www.vivons-maison.com/sites/default/files/styles/740px/public/field/image/appartement-moderne-design.jpg?itok=EIZaSrWD",
      },
      {
        imageId: "ShFft66r3XaeqpTVBcADkrrpqMPChd",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
      {
        imageId: "DitmeOMzktWiokC4zHKikXnuaYbLvH",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
    ],
    details: {
      postDetailsId: "w5o9IQlXvvm3iq5d3st78I1gL2N5Pd",
      machineLaver: "Disponnible",
      refrigerateur: "Disponnible",
      television: "Pas Disponnible",
      chauffeEau: "disponible",
      internetAccess: "Disponnible",
      fibreOptique: "Pas Disponnible",
      autorisationFumer: null,
      etage: "3eme",
      ascenseur: "Disponnible",
      conditions: ["non smoker", "clean", "ensa student", "organized"],
    },
    location: {
      locationId: "sAMbvwAPhNab7ufNz2MqBlcvFHgz1X",
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      coordinates: [-5, 35],
    },
  },
  {
    postId: "5",
    description: "very nice appartement",
    prix: "2500",
    Title: "MODERN APPARTEMENT",
    ville: "Tetouan",
    gender: "homme",
    dateDePublication: "2012-04-23",
    dureeDeDisponibilite: "10days",
    nombreDeCollegues: "2",
    student: {
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      firstName: "Samira",
      lastName: "REHIWA",
      email: "aminebiada98@gmail.com",
      image: "im an image",
      password: "123456",
      gender: "femme",
    },
    images: [
      {
        imageId: "U8ttwpfhM4exDxoqxWlQhBWir6aPb1",
        url: "https://www.vivons-maison.com/sites/default/files/salle-a-manger-appartement-loft.jpg",
      },
      {
        imageId: "ShFft66r3XaeqpTVBcADkrrpqMPChd",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
      {
        imageId: "DitmeOMzktWiokC4zHKikXnuaYbLvH",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
    ],
    details: {
      postDetailsId: "w5o9IQlXvvm3iq5d3st78I1gL2N5Pd",
      machineLaver: "Disponnible",
      refrigerateur: "Disponnible",
      television: "Pas Disponnible",
      chauffeEau: "disponible",
      internetAccess: "Disponnible",
      fibreOptique: "Pas Disponnible",
      autorisationFumer: null,
      etage: "3eme",
      ascenseur: "Disponnible",
      conditions: ["non smoker", "clean", "ensa student", "organized"],
    },
    location: {
      locationId: "sAMbvwAPhNab7ufNz2MqBlcvFHgz1X",
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      coordinates: [-5, 35],
    },
  },
  {
    postId: "6",
    description: "very nice appartement",
    prix: "2660",
    Title: "MODERN APPARTEMENT",
    ville: "Martil",
    gender: "homme",
    dateDePublication: "2012-04-23",
    dureeDeDisponibilite: "10days",
    nombreDeCollegues: "2",
    student: {
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      firstName: "Moha",
      lastName: "SEDIK",
      email: "aminebiada98@gmail.com",
      image: "im an image",
      password: "123456",
      gender: "homme",
    },
    images: [
      {
        imageId: "U8ttwpfhM4exDxoqxWlQhBWir6aPb1",
        url: "https://www.vivons-maison.com/sites/default/files/salle-de-bains-moderne-luxe_0.jpg",
      },
      {
        imageId: "ShFft66r3XaeqpTVBcADkrrpqMPChd",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
      {
        imageId: "DitmeOMzktWiokC4zHKikXnuaYbLvH",
        url: "https://i.pinimg.com/originals/ec/7d/a2/ec7da25b9e98202422fbcdf7cc47fc16.jpg",
      },
    ],
    details: {
      postDetailsId: "w5o9IQlXvvm3iq5d3st78I1gL2N5Pd",
      machineLaver: "Disponnible",
      refrigerateur: "Disponnible",
      television: "Pas Disponnible",
      chauffeEau: "Disponnible",
      internetAccess: "Disponnible",
      tags: [
        "machinelaver",
        "refrigerateur",
        "television",
        "chauffeEau",
        "internetAccess",
        "parking",
      ],
      fibreOptique: "Pas Disponnible",
      autorisationFumer: null,
      etage: "3eme",
      ascenseur: "Disponnible",
      conditions: ["non smoker", "clean", "ensa student", "organized"],
    },
    location: {
      locationId: "sAMbvwAPhNab7ufNz2MqBlcvFHgz1X",
      studentId: "9opKgSJelpKnjxqkn6QGz7OE2hA7WD2sK",
      coordinates: [-5, 35],
    },
  },
];
